import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { createFileRoute, useRouterState } from "@tanstack/react-router";
import {
  Bookmark,
  BookmarkCheck,
  Camera,
  LucideIcon,
  Sparkles,
  Upload,
} from "lucide-react";
import { ChangeEvent, useRef } from "react";
import { AIRecipeSuggestion, validateAuth } from "@/services/api";
import {
  useAddRecipe,
  useAIRecipes,
  useAllRecipes,
  useGenerateAIRecipes,
} from "@/hooks/queries";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { atom, useAtom, useAtomValue, useSetAtom } from "jotai";

// State
const imagePreviewUrlAtom = atom<string | undefined>(undefined);
const ingredientsInputAtom = atom("");

function HomePage() {
  const isNavigatingAway = useRouterState({
    select: (state) =>
      state.location.pathname === "/" ||
      state.location.pathname === "/walkthrough",
  });
  return (
    <div
      className={cn(
        "mx-auto p-6 flex flex-col items-center gap-6 w-full",
        isNavigatingAway && "hidden",
      )}
    >
      <Card className="w-full max-w-5xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="size-5" />
            AI Recipe Generator
          </CardTitle>
          <CardDescription>
            Add ingredients manually, upload a picture, or take a photo to
            auto-detect ingredients.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <ImagePreview />
          <AIInput />
          <DetectedIngredients />
          <AIResults />
        </CardContent>
      </Card>
    </div>
  );
}

function ImagePreview() {
  const imagePreviewUrl = useAtomValue(imagePreviewUrlAtom);
  return (
    <>
      {imagePreviewUrl && (
        <img
          src={imagePreviewUrl}
          alt="Uploaded ingredient preview"
          className="w-full max-h-64 object-cover rounded-md border"
        />
      )}
    </>
  );
}

function AIInput() {
  const setImagePreviewUrl = useSetAtom(imagePreviewUrlAtom);
  const { mutate: submit, isPending } = useGenerateAIRecipes();
  const [ingredientsInput, setIngredientsInput] = useAtom(ingredientsInputAtom);
  return (
    <>
      <Textarea
        value={ingredientsInput}
        onChange={(event) => setIngredientsInput(event.target.value)}
        placeholder="Example: chickpeas, tomato, onion, garlic, cumin"
        className="min-h-28"
      />
      <div className="flex flex-row flex-wrap gap-2">
        <Button
          disabled={ingredientsInput.length === 0 || isPending}
          onClick={() => {
            setImagePreviewUrl(undefined);
            submit(ingredientsInput);
          }}
        >
          {isPending ? "Generating..." : "Generate Recipes"}
        </Button>
        <span className="grow" />
        <ImageUploadButton
          isCamera={false}
          label="Upload Photo"
          icon={Upload}
        />
        <ImageUploadButton isCamera={true} label="Take Photo" icon={Camera} />
      </div>
    </>
  );
}

function DetectedIngredients() {
  const { data, isSuccess } = useAIRecipes();
  return (
    <>
      {isSuccess && data.detected_ingredients.length > 0 && (
        <div className="space-y-1">
          <p className="text-sm font-medium">Detected ingredients</p>
          <p className="text-sm text-muted-foreground">
            {data.detected_ingredients.join(", ")}
          </p>
        </div>
      )}
    </>
  );
}

function AIResults() {
  const { data: recipes, isSuccess } = useAIRecipes();

  return (
    <>
      {isSuccess && recipes.activeModelLabel && (
        <div className="space-y-3">
          {"activeModelLabel" in recipes && (
            <p className="text-sm text-muted-foreground">
              Generated by {recipes.activeModelLabel}
            </p>
          )}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {recipes.recipes.map(
              (recipe: AIRecipeSuggestion, index: number) => (
                <Card key={`${recipe.name}-${index}`}>
                  <CardHeader>
                    <CardTitle>{recipe.name}</CardTitle>
                    <CardDescription>{recipe.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <p className="font-medium">Ingredients</p>
                      <ul className="list-disc list-inside text-sm text-muted-foreground">
                        {recipe.ingredients.map(
                          (ingredient, ingredientIndex) => (
                            <li key={`${ingredient}-${ingredientIndex}`}>
                              {ingredient}
                            </li>
                          ),
                        )}
                      </ul>
                    </div>
                    <div>
                      <p className="font-medium">Steps</p>
                      <ol className="list-decimal list-inside text-sm text-muted-foreground space-y-1">
                        {recipe.steps.map((step, stepIndex) => (
                          <li key={`${stepIndex}-${step}`}>{step}</li>
                        ))}
                      </ol>
                    </div>
                    <SaveButton suggestion={recipe} />
                  </CardContent>
                </Card>
              ),
            )}
          </div>
        </div>
      )}
    </>
  );
}

function SaveButton({ suggestion }: { suggestion: AIRecipeSuggestion }) {
  const { mutate: addRecipe, isSuccess: wasSaved } = useAddRecipe();

  // TODO: This is not a correct way to handle this.  We need the AI to
  //       generate real recipe objects with steps and ingredients.
  function handleAdd() {
    const payload = {
      name: suggestion.name,
      description: suggestion.description,
      rating: 0,
      inPlan: false,
      ingredients: suggestion.ingredients.map((ingredient, index) => ({
        id: index,
        name: ingredient,
        amount: 1,
        unit: null,
      })),
      steps: suggestion.steps.map((step, index) => ({
        id: index,
        description: step,
        time: null,
      })),
    };

    addRecipe(payload);
  }

  const SavedIcon = wasSaved ? BookmarkCheck : Bookmark;

  return (
    <Button className="w-full" disabled={wasSaved} onClick={() => handleAdd()}>
      <SavedIcon className="h-4 w-4 mr-2" />
      {wasSaved ? "Saved" : "Save"}
    </Button>
  );
}

function ImageUploadButton({
  isCamera,
  label,
  icon: Icon,
}: {
  isCamera: boolean;
  label: string;
  icon: LucideIcon;
}) {
  const setImagePreviewUrl = useSetAtom(imagePreviewUrlAtom);
  const setIngredientsInput = useSetAtom(ingredientsInputAtom);
  const { mutate: submit, isPending } = useGenerateAIRecipes();
  const inputRef = useRef<HTMLInputElement>(null);

  const handleImageSelect = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file || isPending) {
      return;
    }

    if (!file.type.startsWith("image/")) {
      toast.error("Please select an image file");
      return;
    }

    const preview = URL.createObjectURL(file);
    setImagePreviewUrl(preview);
    setIngredientsInput("");
    submit(file);
  };

  return (
    <Button
      variant="outline"
      disabled={isPending}
      onClick={() => inputRef?.current?.click()}
    >
      <input
        ref={inputRef}
        type="file"
        accept="image/*"
        capture={isCamera ? "environment" : undefined}
        className="hidden"
        onChange={handleImageSelect}
      />
      <Icon className="size-4" /> {label}
    </Button>
  );
}

export const Route = createFileRoute("/home")({
  beforeLoad: validateAuth,
  component: HomePage,
});
