import RecommentationCard from "@/components/RecommendationCard";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useFeedIds } from "@/hooks/queries";
import { AIRecipeSuggestion, aiAPI } from "@/services/api";

function HomePage() {
  const { data: recommendations, isLoading } = useFeedIds();
  const [ingredientsInput, setIngredientsInput] = useState("");

  const ingredientList = useMemo(
    () =>
      ingredientsInput
        .split(/,|\n/g)
        .map((item) => item.trim())
        .filter(Boolean),
    [ingredientsInput],
  );

  const aiRecipesMutation = useMutation({
    mutationFn: async () => {
      const response = await aiAPI.generateRecipes({
        ingredients: ingredientList,
        max_recipes: 5,
      });
      return response.data;
    },
  });

  const handleGenerate = () => {
    if (ingredientList.length === 0 || aiRecipesMutation.isPending) {
      return;
    }
    aiRecipesMutation.mutate();
  };

  if (isLoading || !recommendations) return <div>Loading...</div>;
  return (
    <div className="mx-auto p-6 flex flex-col items-center gap-6 w-full">
      <Card className="w-full max-w-5xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="size-5" />
            AI Recipe Generator
          </CardTitle>
          <CardDescription>
            Add ingredients separated by commas or new lines to generate recipe
            ideas.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            value={ingredientsInput}
            onChange={(event) => setIngredientsInput(event.target.value)}
            placeholder="Example: chickpeas, tomato, onion, garlic, cumin"
            className="min-h-28"
          />
          <Button
            onClick={handleGenerate}
            disabled={ingredientList.length === 0 || aiRecipesMutation.isPending}
          >
            {aiRecipesMutation.isPending ? "Generating..." : "Generate Recipes"}
          </Button>

          {aiRecipesMutation.isError && (
            <p className="text-sm text-destructive">
              {(aiRecipesMutation.error as any)?.response?.data?.detail ||
                "Could not generate recipes right now."}
            </p>
          )}

          {aiRecipesMutation.data && (
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">
                Generated by {aiRecipesMutation.data.model}
              </p>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {aiRecipesMutation.data.recipes.map(
                  (recipe: AIRecipeSuggestion, index: number) => (
                    <Card key={`${recipe.name}-${index}`}>
                      <CardHeader>
                        <CardTitle>{recipe.name}</CardTitle>
                        <CardDescription>{recipe.description}</CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-3">
                        <div>
                          <p className="font-medium">Ingredients</p>
                          <ul className="list-disc list-inside text-sm text-muted-foreground">
                            {recipe.ingredients.map((ingredient, ingredientIndex) => (
                              <li key={`${ingredient}-${ingredientIndex}`}>
                                {ingredient}
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <p className="font-medium">Steps</p>
                          <ol className="list-decimal list-inside text-sm text-muted-foreground space-y-1">
                            {recipe.steps.map((step, stepIndex) => (
                              <li key={`${stepIndex}-${step}`}>{step}</li>
                            ))}
                          </ol>
                        </div>
                      </CardContent>
                    </Card>
                  ),
                )}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {recommendations.map((id, i) => (
        <RecommentationCard key={i} recipeId={id} orientation={i % 2 === 0} />
      ))}
    </div>
  );
}

export const Route = createFileRoute("/home")({ component: HomePage });
