import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { createFileRoute, useRouterState } from "@tanstack/react-router";
import { Camera, LucideIcon, Sparkles, Upload } from "lucide-react";
import { ChangeEvent, useRef, useState } from "react";
import { AIRecipeSuggestion, validateAuth } from "@/services/api";
import { useAIRecipes, useGenerateAIRecipes } from "@/hooks/queries";
import { toast } from "sonner";
import { useIsMutating } from "@tanstack/react-query";
import { cn } from "@/lib/utils";

function HomePage() {
  const isNavigatingAway = useRouterState({
    select: (state) =>
      state.location.pathname === "/" ||
      state.location.pathname === "/walkthrough",
  });
  const [imagePreviewUrl, setImagePreviewUrl] = useState<string | undefined>(
    undefined,
  );
  return (
    <div
      className={cn(
        "mx-auto p-6 flex flex-col items-center gap-6 w-full",
        isNavigatingAway && "hidden",
      )}
    >
      <Card className="w-full max-w-5xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="size-5" />
            AI Recipe Generator
          </CardTitle>
          <CardDescription>
            Add ingredients manually, upload a picture, or take a photo to
            auto-detect ingredients.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <ImagePreview imagePreviewUrl={imagePreviewUrl} />
          <AIInput setImagePreviewUrl={setImagePreviewUrl} />
          <DetectedIngredients />
          <AIResults />
        </CardContent>
      </Card>
    </div>
  );
}

function ImagePreview({ imagePreviewUrl }: { imagePreviewUrl?: string }) {
  return (
    <>
      {imagePreviewUrl && (
        <img
          src={imagePreviewUrl}
          alt="Uploaded ingredient preview"
          className="w-full max-h-64 object-cover rounded-md border"
        />
      )}
    </>
  );
}

function AIInput({
  setImagePreviewUrl,
}: {
  setImagePreviewUrl: (url: string | undefined) => void;
}) {
  const { mutate: submit } = useGenerateAIRecipes();
  const count = useIsMutating({ mutationKey: ["generateAIRecipes"] });
  const isGenerating = count > 0;
  const [ingredientsInput, setIngredientsInput] = useState("");
  return (
    <>
      <Textarea
        value={ingredientsInput}
        onChange={(event) => setIngredientsInput(event.target.value)}
        placeholder="Example: chickpeas, tomato, onion, garlic, cumin"
        className="min-h-28"
      />
      <div className="flex flex-row flex-wrap gap-2">
        <Button
          disabled={ingredientsInput.length === 0 || isGenerating}
          onClick={() => {
            setImagePreviewUrl(undefined);
            submit(ingredientsInput);
          }}
        >
          {isGenerating ? "Generating..." : "Generate Recipes"}
        </Button>
        <span className="grow" />
        <ImageUploadButton
          isCamera={false}
          label="Upload Photo"
          icon={Upload}
          setImagePreviewUrl={setImagePreviewUrl}
          setIngredientsInput={setIngredientsInput}
        />
        <ImageUploadButton
          isCamera={true}
          label="Take Photo"
          icon={Camera}
          setImagePreviewUrl={setImagePreviewUrl}
          setIngredientsInput={setIngredientsInput}
        />
      </div>
    </>
  );
}

function DetectedIngredients() {
  const { data, isSuccess } = useAIRecipes();
  return (
    <>
      {isSuccess && data.detected_ingredients.length > 0 && (
        <div className="space-y-1">
          <p className="text-sm font-medium">Detected ingredients</p>
          <p className="text-sm text-muted-foreground">
            {data.detected_ingredients.join(", ")}
          </p>
        </div>
      )}
    </>
  );
}

function AIResults() {
  const { data: recipes, isSuccess } = useAIRecipes();

  return (
    <>
      {isSuccess && recipes.activeModelLabel && (
        <div className="space-y-3">
          {"activeModelLabel" in recipes && (
            <p className="text-sm text-muted-foreground">
              Generated by {recipes.activeModelLabel}
            </p>
          )}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {recipes.recipes.map(
              (recipe: AIRecipeSuggestion, index: number) => (
                <Card key={`${recipe.name}-${index}`}>
                  <CardHeader>
                    <CardTitle>{recipe.name}</CardTitle>
                    <CardDescription>{recipe.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div>
                      <p className="font-medium">Ingredients</p>
                      <ul className="list-disc list-inside text-sm text-muted-foreground">
                        {recipe.ingredients.map(
                          (ingredient, ingredientIndex) => (
                            <li key={`${ingredient}-${ingredientIndex}`}>
                              {ingredient}
                            </li>
                          ),
                        )}
                      </ul>
                    </div>
                    <div>
                      <p className="font-medium">Steps</p>
                      <ol className="list-decimal list-inside text-sm text-muted-foreground space-y-1">
                        {recipe.steps.map((step, stepIndex) => (
                          <li key={`${stepIndex}-${step}`}>{step}</li>
                        ))}
                      </ol>
                    </div>
                  </CardContent>
                </Card>
              ),
            )}
          </div>
        </div>
      )}
    </>
  );
}

function ImageUploadButton({
  isCamera,
  label,
  icon: Icon,
  setImagePreviewUrl,
  setIngredientsInput,
}: {
  isCamera: boolean;
  label: string;
  icon: LucideIcon;
  setImagePreviewUrl: (url: string | undefined) => void;
  setIngredientsInput: (ingredientsInput: string) => void;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const { mutate: submit } = useGenerateAIRecipes();
  const count = useIsMutating({ mutationKey: ["generateAIRecipes"] });
  const isGenerating = count > 0;

  const handleImageSelect = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file || isGenerating) {
      return;
    }

    if (!file.type.startsWith("image/")) {
      toast.error("Please select an image file");
      return;
    }

    const preview = URL.createObjectURL(file);
    setImagePreviewUrl(preview);
    setIngredientsInput("");
    submit(file);
  };

  return (
    <Button
      variant="outline"
      disabled={isGenerating}
      onClick={() => inputRef?.current?.click()}
    >
      <input
        ref={inputRef}
        type="file"
        accept="image/*"
        capture={isCamera ? "environment" : undefined}
        className="hidden"
        onChange={handleImageSelect}
      />
      <Icon className="size-4" /> {label}
    </Button>
  );
}

export const Route = createFileRoute("/home")({
  beforeLoad: validateAuth,
  component: HomePage,
});
